PROJECT_NAME := health_fitness

# EXTRA_COMPONENT_DIRS = $(IDF_PATH)/examples/system/console/components
# EXTRA_COMPONENT_DIRS += $(IDF_PATH)/examples/wifi/iperf/components


include $(HDF_PATH)/project.mk
